create table t_seg_contratacao
(
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_cliente     number      NOT NULL,
    id_seguro      number      NOT NULL,
    dt_contratacao DATE        NOT NULL,
    status         varchar(50) NOT NULL,
    primary key (id),
    foreign key (id_cliente) references t_seg_cliente (id),
    foreign key (id_seguro) references t_seg_seguro (id)

);