create table t_seg_contratacao
(
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    cliente        number(3,1),
    seguro         number(3,1),
    dt_contratacao DATE               NOT NULL,
    status         varchar(50) UNIQUE NOT NULL,
    primary key (id)

);