create table t_seg_cliente
(
    id            number GENERATED BY DEFAULT AS IDENTITY,
    nome          varchar2(255) NOT NULL,
    cpf           varchar2(11) NOT NULL,
    dt_nascimento DATE NOT NULL,
    email         VARCHAR2(100) NOT NULL,
    endereco      VARCHAR2(200) NOT NULL,
    PRIMARY KEY (id)
);