create table t_seg_sinistro
(
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_contratacao number       NOT NULL,
    descricao      varchar(250) NOT NULL,
    status         varchar(50)  NOT NULL,
    valor          number(8,2)        NOT NULL,
    primary key (id),
    foreign key (id_contratacao) references t_seg_contratacao (id)
);