create table t_seg_cliente
(
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome          VARCHAR2(255) NOT NULL,
    cpf           VARCHAR2(11) NOT NULL,
    dt_nascimento DATE NOT NULL,
    email         VARCHAR2(100) NOT NULL,
    endereco      VARCHAR2(200) NOT NULL,
    PRIMARY KEY (id)
);
